apiVersion: v1
kind: Service
metadata:
  name: iweblens-service
  labels:
      app: iweblens-service 
spec:
  selector:
    app: iweblens
  type: NodePort
  ports:
  - nodePort: 30001 
    port: 80
    targetPort: 5000
  